version: "2"

formatters:
  enable:
    - gofmt
    - gci

linters:
  # https://golangci-lint.run/docs/linters/
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - revive
    - mirror
    - usestdlibvars
    - misspell
    - dupword
    - loggercheck
    - exptostd
    - bodyclose
    - noctx
    - wrapcheck
    - errorlint
    - exhaustive
    - prealloc
    - unconvert
linters-settings:
  revive:
    # https://github.com/mgechev/revive/blob/HEAD/RULES_DESCRIPTIONS.md
    rules:
      - name: blank-imports
      - name: context-as-argument
        arguments:
          - allowTypesBefore: "*testing.T"
      - name: context-keys-type
      - name: dot-imports
      - name: empty-block
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: exported
        arguments:
          - "sayRepetitiveInsteadOfStutters"
      - name: increment-decrement
      - name: indent-error-flow
      - name: range
      - name: receiver-naming
      - name: redefines-builtin-id
      - name: superfluous-else
      - name: time-naming
      - name: unexported-return
      - name: unreachable-code
      - name: unused-parameter
      - name: var-declaration
      - name: var-naming
  misspell:
    locale: UK

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - wrapcheck
