// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlc

import (
	"context"
)

const countUserByUsername = `-- name: CountUserByUsername :one
SELECT count(*) FROM users
WHERE username = $1
`

func (q *Queries) CountUserByUsername(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRow(ctx, countUserByUsername, username)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserAndReturnId = `-- name: CreateUserAndReturnId :one
INSERT INTO users (
  username, email, password
) VALUES (
    $1, $2, $3
)
RETURNING id
`

type CreateUserAndReturnIdParams struct {
	Username string
	Email    string
	Password string
}

func (q *Queries) CreateUserAndReturnId(ctx context.Context, arg CreateUserAndReturnIdParams) (int64, error) {
	row := q.db.QueryRow(ctx, createUserAndReturnId, arg.Username, arg.Email, arg.Password)
	var id int64
	err := row.Scan(&id)
	return id, err
}
