// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/google/uuid"
)

type UsedRefreshToken struct {
	ID  int64
	Jti uuid.UUID
}

type User struct {
	ID       int64
	Username string
	Email    string
	Password string
}
