// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
)

const countUsedRefreshTokenByJTI = `-- name: CountUsedRefreshTokenByJTI :one
SELECT count(*) FROM used_refresh_tokens
WHERE jti = $1
`

func (q *Queries) CountUsedRefreshTokenByJTI(ctx context.Context, jti uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsedRefreshTokenByJTI, jti)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserByUsername = `-- name: CountUserByUsername :one
SELECT count(*) FROM users
WHERE username = $1
`

func (q *Queries) CountUserByUsername(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRow(ctx, countUserByUsername, username)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserAndReturnId = `-- name: CreateUserAndReturnId :one
INSERT INTO users (
  username, email, password
) VALUES (
    $1, $2, $3
)
RETURNING id
`

type CreateUserAndReturnIdParams struct {
	Username string
	Email    string
	Password string
}

func (q *Queries) CreateUserAndReturnId(ctx context.Context, arg CreateUserAndReturnIdParams) (int64, error) {
	row := q.db.QueryRow(ctx, createUserAndReturnId, arg.Username, arg.Email, arg.Password)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findUserByUsername = `-- name: FindUserByUsername :one
SELECT id, username, email, password FROM users
WHERE username = $1
`

func (q *Queries) FindUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, email, password FROM users
WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const markTokenAsUsed = `-- name: MarkTokenAsUsed :exec
INSERT INTO used_refresh_tokens (
    jti
) VALUES (
    $1
)
`

func (q *Queries) MarkTokenAsUsed(ctx context.Context, jti uuid.UUID) error {
	_, err := q.db.Exec(ctx, markTokenAsUsed, jti)
	return err
}
