// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package postgres

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const closeSession = `-- name: CloseSession :one
UPDATE sessions
SET
    status = 'closed',
    updated_at = now()
WHERE public_id = $1
RETURNING public_id
`

func (q *Queries) CloseSession(ctx context.Context, publicID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, closeSession, publicID)
	var public_id uuid.UUID
	err := row.Scan(&public_id)
	return public_id, err
}

const countClosedSessionByPublicID = `-- name: CountClosedSessionByPublicID :one
SELECT count(*) FROM sessions
WHERE public_id = $1 AND status = 'closed'
`

func (q *Queries) CountClosedSessionByPublicID(ctx context.Context, publicID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countClosedSessionByPublicID, publicID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsedRefreshTokenByJTI = `-- name: CountUsedRefreshTokenByJTI :one
SELECT count(*) FROM used_refresh_tokens
WHERE jti = $1
`

func (q *Queries) CountUsedRefreshTokenByJTI(ctx context.Context, jti uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsedRefreshTokenByJTI, jti)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserByUsername = `-- name: CountUserByUsername :one
SELECT count(*) FROM users
WHERE username = $1
`

func (q *Queries) CountUserByUsername(ctx context.Context, username string) (int64, error) {
	row := q.db.QueryRow(ctx, countUserByUsername, username)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    user_id, public_id, created_at, updated_at, status
) VALUES (
    $1, $2, $3, $4, 'active'
)
RETURNING id
`

type CreateSessionParams struct {
	UserID    int64
	PublicID  uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (int64, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.PublicID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createUserAndReturnId = `-- name: CreateUserAndReturnId :one
INSERT INTO users (
  username, email, password
) VALUES (
    $1, $2, $3
)
RETURNING id
`

type CreateUserAndReturnIdParams struct {
	Username string
	Email    string
	Password string
}

func (q *Queries) CreateUserAndReturnId(ctx context.Context, arg CreateUserAndReturnIdParams) (int64, error) {
	row := q.db.QueryRow(ctx, createUserAndReturnId, arg.Username, arg.Email, arg.Password)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findUserByUsername = `-- name: FindUserByUsername :one
SELECT id, username, email, password FROM users
WHERE username = $1
`

func (q *Queries) FindUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const getAllSessionsByUserId = `-- name: GetAllSessionsByUserId :many
SELECT id, user_id, status, public_id, created_at, updated_at FROM sessions
WHERE user_id = $1
`

func (q *Queries) GetAllSessionsByUserId(ctx context.Context, userID int64) ([]Session, error) {
	rows, err := q.db.Query(ctx, getAllSessionsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.PublicID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserById = `-- name: GetUserById :one
SELECT id, username, email, password FROM users
WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
	)
	return i, err
}

const markTokenAsUsed = `-- name: MarkTokenAsUsed :exec
INSERT INTO used_refresh_tokens (
    jti
) VALUES (
    $1
)
`

func (q *Queries) MarkTokenAsUsed(ctx context.Context, jti uuid.UUID) error {
	_, err := q.db.Exec(ctx, markTokenAsUsed, jti)
	return err
}
